services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
  rag:
    build: .
    volumes: 
      - ./input_pdfs:/app/input_pdfs
      - ./output_jsons:/app/output_jsons
    env_file:
      - .env
    environment:
      - RUN_INGEST=True
    depends_on:
      - qdrant

volumes:
  qdrant_storage:

      